update latest to the module.sh version respecting whitespace

diff --git a/latest b/latest
--- a/latest
+++ b/latest
@@ -4,7 +4,7 @@
 # is only being used in the static version
 
 # define a function called 'module' which does exactly what module-core does
-# start module https://mdl.sh/module/core/module-core-0.9.17.sh
+# start module https://mdl.sh/development/module/core/module-core-0.9.19.sh
 module() {
 # guarantees: intentional-side-effects
 
@@ -15,7 +15,7 @@ eval "$(
 	src="$(
 		set -eu
 
-# start module https://mdl.sh/error/error-1.0.3.sh
+# start module https://mdl.sh/development/error/error-1.0.4.sh
 error() {
 # guarantees: intentional-side-effects
 
@@ -30,23 +30,36 @@ error() {
 printf '%s\n' "$1" >&2
 exit "${2:-1}"
 }
-# end module https://mdl.sh/error/error-1.0.3.sh
-# start module https://mdl.sh/module/fetch/module-fetch-0.9.16.sh
+# end module https://mdl.sh/development/error/error-1.0.4.sh
+# start module https://mdl.sh/development/module/fetch/module-fetch-0.9.21.sh
 moduleFetch() { (
 set -eu
+# check number of arguments
+if [ "$#" -ne 1 ]; then
+	printf 'Invalid number of arguments\n' >&2
+	exit 64
+fi
+
 # mandatory parameters
 url="$1"
 
 # dependencies
-# start module https://mdl.sh/colon-config/colon-config-evaluated-0.9.6.sh
+if [ "$(command -v module 2>/dev/null | cut -c1)" = "/" ]; then eval "$(module init)"; elif ! command -v module >/dev/null 2>&1; then eval "$(h=mdl.sh; p=/latest; u="https://$h$p"; curl -fsL "$u" || wget -q "$u" -O - || ( printf 'GET %s HTTP/1.1\r\nHost: %s\r\nConnection: close\r\n\r\n' "$p" "$h" | openssl s_client -quiet -connect "$h:443" 2>/dev/null | sed '1,/^\r$/d') )"; fi
+# start module https://mdl.sh/config/colon/colon-config-evaluated/colon-config-evaluated-0.9.8.sh
 colonConfigEvaluated() { (
 set -eu
 # parameters are defined in colon-config
 
 # dependencies
-# start module https://mdl.sh/colon-config/colon-config-0.9.4.sh
+# start module https://mdl.sh/config/colon/colon-config/colon-config-0.9.6.sh
 colonConfig() { (
 set -eu
+# example usage: colonConfig user ~/.example.conf /etc/example.conf anonymous
+# key     = user
+# config1 = ~/.example.conf
+# config2 = /etc/example.conf
+# default = anonymous
+
 if [ "$#" -lt 2 ]; then
 	printf 'This function requires at least two arguments.\n' >&2
 	exit 1
@@ -59,14 +72,13 @@ fi
 key="$1"
 shift 1
 
-# example usage: colonConfig user ~/.example.conf /etc/example.conf anonymous
-# key     = user
-# config1 = ~/.example.conf
-# config2 = /etc/example.conf
-# default = anonymous
+envVarName="CONFIG_$(printf '%s' "$key" | tr 'a-z-' 'A-Z_')"
+# return the value of the corresponding environment variable if it exists
+# shellcheck disable=SC2016
+eval "$(printf 'if [ ! -z ${%s+x} ]; then printf '"'"'%%s\n'"'"' "${%s}"; exit 0; fi' "$envVarName" "$envVarName")"
 
 # dependencies
-# start module https://mdl.sh/colon-config/colon-value-0.9.2.sh
+# start module https://mdl.sh/config/colon/colon-value/colon-value-0.9.3.sh
 colonValue() { (
 set -eu
 # mandatory parameters
@@ -83,8 +95,8 @@ grep -e "^$key:" "$file" \
 	| cut -d':' -f2- \
 	| sed -e 's/^[[:space:]]\{1,\}//g' -e 's/[[:space:]]\{1,\}$//g'
 ) }
-# end module https://mdl.sh/colon-config/colon-value-0.9.2.sh
-# start module https://mdl.sh/colon-config/colon-value-exists-0.9.0.sh
+# end module https://mdl.sh/config/colon/colon-value/colon-value-0.9.3.sh
+# start module https://mdl.sh/config/colon/colon-value-exists/colon-value-exists-0.9.0.sh
 colonValueExists() { (
 set -eu
 # mandatory parameters
@@ -102,7 +114,7 @@ grep -e "^$key:" "$file" >/dev/null
 # use the return value to signal success and failure
 exit $?
 ) }
-# end module https://mdl.sh/colon-config/colon-value-exists-0.9.0.sh
+# end module https://mdl.sh/config/colon/colon-value-exists/colon-value-exists-0.9.0.sh
 
 # try to find the key in the list of config files
 while [ "$#" -gt 1 ]; do
@@ -119,20 +131,27 @@ done
 defaultValue="$1"
 printf '%s\n' "$defaultValue"
 ) }
-# end module https://mdl.sh/colon-config/colon-config-0.9.4.sh
+# end module https://mdl.sh/config/colon/colon-config/colon-config-0.9.6.sh
 
 value="$(colonConfig "$@")"
 eval "printf '%s ' $value | sed 's/ \$//' " # to evaluate variables like: $XDG_DATA_HOME
 printf '\n' # and terminate with a newline
 ) }
-# end module https://mdl.sh/colon-config/colon-config-evaluated-0.9.6.sh
-# start module https://mdl.sh/https-get/https-get-1.0.5.sh
+# end module https://mdl.sh/config/colon/colon-config-evaluated/colon-config-evaluated-0.9.8.sh
+# start module https://mdl.sh/network/https-get/https-get-1.0.7.sh
 httpsGet() { (
 set -eu
-# mandatory:
+# check number of arguments
+if [ "$#" -ne 1 ]; then
+	printf 'Invalid number of arguments\n' >&2
+	exit 64
+fi
+
+# mandatory parameters
 url="$1"
 
-# start module https://mdl.sh/error/error-1.0.3.sh
+# dependencies
+# start module https://mdl.sh/development/error/error-1.0.4.sh
 error() {
 # guarantees: intentional-side-effects
 
@@ -147,14 +166,39 @@ error() {
 printf '%s\n' "$1" >&2
 exit "${2:-1}"
 }
-# end module https://mdl.sh/error/error-1.0.3.sh
+# end module https://mdl.sh/development/error/error-1.0.4.sh
+# start module https://mdl.sh/development/debug/debug-1.0.0.sh
+debug() {
+# guarantees: intentional-side-effects
+# To understand this code please take a look at the README.md
+
+if [ "$#" -gt 0 ] &&  [ "$(eval "printf '%s\\n' \"\${DEBUG_${3:-${DEBUG_NAMESPACE:-ALL}}:-$(printf '%s' "${DEBUG_ALL:-0}")}\"")" -ge "${2:-1}" ]; then
+	printf '%s: %s\n' "${3:-${DEBUG_NAMESPACE:-ALL}}" "$1" >&2
+fi
+}
+# end module https://mdl.sh/development/debug/debug-1.0.0.sh
+
+# The debug module uses this variable
+export DEBUG_NAMESPACE="HTTPS_GET"
+
+# check if it is an https url
+if [ "$(printf '%s' "$url" | head -c 8 | tr '[:upper:]' '[:lower:]')" != "https://" ]; then
+	error "'$url' does not start with 'https://'. Exiting." 65
+fi
+
+rc="1"
 
 # find out command- v http client is available and use it
 if command -v curl >/dev/null 2>&1; then
+	debug "Using curl" 1
 	curl -sL "$url"
+	rc="$?"
 elif command -v wget >/dev/null 2>&1; then
+	debug "Using wget" 1
 	wget -qO - "$url"
+	rc="$?"
 elif command -v openssl >/dev/null 2>&1; then
+	debug "Using openssl" 1
 	host="$(printf '%s\n' "$url" | sed -e 's;^[^/]\{1,\}://;;' -e 's;[/:].*$;;')"
 	path="$(printf '%s\n' "$url" | sed -e 's;^[^/]\{1,\}://[^/]\{1,\}/;/;')" # with leading /
 	port="$(printf '%s\n' "$url" | sed -e 's;^[^/]\{1,\}://[^/]\{1,\}:\([0-9]\{1,\}\)/.*$;\1;')"
@@ -162,14 +206,26 @@ elif command -v openssl >/dev/null 2>&1; then
 		port="443"
 	fi
 
-	# sed to remove the headers form the output
+	# sed to remove the headers from the output
 	printf 'GET %s HTTP/1.1\r\nHost: %s\r\nConnection: close\r\n\r\n' "$path" "$host" | openssl s_client -quiet -connect "$host:$port" 2>/dev/null | sed '1,/^\r$/d'
+	rc="$?"
+elif command -v ftp >/dev/null 2>&1 && [ "$(ftp -h 2>&1 | grep -c http)" -gt 0 ]; then
+	# if the cli program 'ftp' exists, we try to find out if it is the correct version (OpenBSD vs. GNU)
+	debug "Using ftp" 1
+	ftp -o - "$url"
+	rc="$?"
 else
 	error "None of curl, wget and openssl is available. Exiting."
 fi
+
+if [ "$rc" -ne 0 ]; then
+	debug "Non-zero rc '$rc', replacing it now" 1
+	# actually we don't know the exact reason why it failed, but unavailability is the most common/likely
+	exit 69
+fi
 ) }
-# end module https://mdl.sh/https-get/https-get-1.0.5.sh
-# start module https://mdl.sh/error/error-1.0.3.sh
+# end module https://mdl.sh/network/https-get/https-get-1.0.7.sh
+# start module https://mdl.sh/development/error/error-1.0.4.sh
 error() {
 # guarantees: intentional-side-effects
 
@@ -184,8 +240,8 @@ error() {
 printf '%s\n' "$1" >&2
 exit "${2:-1}"
 }
-# end module https://mdl.sh/error/error-1.0.3.sh
-# start module https://mdl.sh/tmp-dir-by-user-keyword/tmp-dir-by-user-keyword-0.9.4.sh
+# end module https://mdl.sh/development/error/error-1.0.4.sh
+# start module https://mdl.sh/development/polyfill/tmp-dir-by-user-keyword/tmp-dir-by-user-keyword-0.9.5.sh
 tmpDirByUserKeyword() { (
 set -eu
 # This module provides an easy way to create a tmp directory
@@ -211,6 +267,7 @@ fi
 
 # macOS gets some special treatment
 # $OSTYPE is not part of POSIX
+# shellcheck disable=SC2039
 if [ "$(printf '%s' "${OSTYPE:-}" | cut -c 1-6)" = "darwin" ]; then
 	cmdDry="$(printf "mktemp -t '%s' -u" "$keyword")"
 	cmdDir="$(printf "mktemp -d -t '%s'" "$keyword")"
@@ -260,8 +317,8 @@ fi
 
 printf '%s\n' "$pointer"
 ) }
-# end module https://mdl.sh/tmp-dir-by-user-keyword/tmp-dir-by-user-keyword-0.9.4.sh
-# start module https://mdl.sh/cache/cache-0.9.6.sh
+# end module https://mdl.sh/development/polyfill/tmp-dir-by-user-keyword/tmp-dir-by-user-keyword-0.9.5.sh
+# start module https://mdl.sh/development/cache/cache-0.9.7.sh
 cache() { (
 set -eu
 # Make is easy to cache the result of a command
@@ -284,7 +341,7 @@ else
 fi
 
 # for POSIX compatibility
-# start module https://mdl.sh/printfq/printfq-0.9.3.sh
+# start module https://mdl.sh/development/polyfill/POSIX/printfq/printfq-0.9.4.sh
 printfq() { (
 set -eu
 # This module tries to replicate the sh_quote behaivor of printf '%q ' "$@" for data without new lines
@@ -304,7 +361,7 @@ do
 done
 printf '\n'
 ) }
-# end module https://mdl.sh/printfq/printfq-0.9.3.sh
+# end module https://mdl.sh/development/polyfill/POSIX/printfq/printfq-0.9.4.sh
 
 # Parameter default values
 cacheDir="${cacheDir:-./cache}"
@@ -399,8 +456,8 @@ fi
 
 cat "$cacheFile"
 ) }
-# end module https://mdl.sh/cache/cache-0.9.6.sh
-# start module https://mdl.sh/debug/debug-1.0.0.sh
+# end module https://mdl.sh/development/cache/cache-0.9.7.sh
+# start module https://mdl.sh/development/debug/debug-1.0.0.sh
 debug() {
 # guarantees: intentional-side-effects
 # To understand this code please take a look at the README.md
@@ -409,10 +466,46 @@ if [ "$#" -gt 0 ] &&  [ "$(eval "printf '%s\\n' \"\${DEBUG_${3:-${DEBUG_NAMESPAC
 	printf '%s: %s\n' "${3:-${DEBUG_NAMESPACE:-ALL}}" "$1" >&2
 fi
 }
-# end module https://mdl.sh/debug/debug-1.0.0.sh
+# end module https://mdl.sh/development/debug/debug-1.0.0.sh
+# start module https://mdl.sh/content/transformer/whitespace-protection/whitespace-protection-0.9.1.sh
+whitespaceProtection() { (
+set -eu
+set -eu
+
+# check number of arguments
+if [ "$#" -lt 1 ] || [ "$#" -gt 2 ]; then
+	printf 'Invalid number of arguments\n' >&2
+	exit 64
+fi
+
+# mandatory parameters
+action="$1"
+
+if [ "$action" = "add" ]; then
+	# add the strings before and after the input
+	printf '%s' "AAA"
+	cat -
+	printf '%s' "ZZZ"
+elif [ "$action" = "remove" ]; then
+	# remove the protection string before and after the content
+	input="$(cat -)"
+	input="${input#AAA}"
+	input="${input%ZZZ}"
+	printf '%s' "$input"
+else
+	printf 'Invalid argument (neither "add" nor "remove")\n' >&2
+	exit 64
+fi
+) }
+# end module https://mdl.sh/content/transformer/whitespace-protection/whitespace-protection-0.9.1.sh
 
 # The debug module uses this variable
 export DEBUG_NAMESPACE="MODULE_FETCH"
+
+# check if it is an https url
+if [ "$(printf '%s' "$url" | head -c 8 | tr '[:upper:]' '[:lower:]')" != "https://" ]; then
+	error "'$url' does not start with 'https://'. Exiting." 65
+fi
 
 debug "Getting module from URL '$url'" 1
 
@@ -432,7 +525,7 @@ if [ -f "$userConfig" ]; then
 			debug "Using local repository '$moduleFile'" 1
 
 			# read file
-			src="$(cat "$moduleFile")"
+			src="$(whitespaceProtection add <"$moduleFile")"
 
 			# set executed
 			executed="true"
@@ -453,7 +546,10 @@ if [ "$executed" = "false" ] && ( command -v md5sum >/dev/null 2>&1 || command -
 	if cachePointer="$(tmpDirByUserKeyword "module-cache" 2>/dev/null)"; then
 		debug "Using cache directory '$cachePointer'" 1
 		# execute with cache
-		src="$(cache -d "$cachePointer" -- httpsGet "$url")"
+		# tunnel the return value of httpsGet through the pipe:
+		# https://unix.stackexchange.com/questions/14270/get-exit-status-of-process-thats-piped-to-another/70675#70675
+		# shellcheck disable=SC2086
+		src="$( ( ( ( ( cache -d "$cachePointer" -s "httpsGet '$url'"; printf '%s\n' "$?" >&3 ) | whitespaceProtection add >&4 ) 3>&1 ) | ( read -r rc ; exit $rc ) ) 4>&1; )" || exit $?
 		executed="true"
 	else
 		debug "tmpDirByUserKeyword failed" 1
@@ -463,7 +559,8 @@ fi
 # if the command was not executed with the cache, we just skip the cache
 if [ "$executed" = "false" ]; then
 	debug "Getting module without cache" 1
-	src="$(httpsGet "$url")"
+	# same return code tunnel as 10 lines above
+	src="$( ( ( (httpsGet "$url"; printf '%s' "$?" >&3 ) | whitespaceProtection add >&4) 3>&1) | ( read -r rc ; exit "$rc" ) 4>&1; )" || exit $?
 fi
 
 # In order to elimiate common server errors we check for the script header
@@ -474,16 +571,16 @@ resourceShebangs='#!/usr/bin/env bash
 #!/bin/sh
 #!/usr/bin/bash
 #!/usr/bin/sh'
-firstLine="$(printf '%s\n' "$src" | head -n1)"
+firstLine="$(printf '%s' "$src" | whitespaceProtection remove | head -n1)"
 if ! (printf '%s\n' "$resourceShebangs" | grep -F -q -x "$firstLine") ; then
-	error "For the URL '$url': the first line '$firstLine' is not part of the allowed headers. Exiting."
+	error "For the URL '$url': the first line '$firstLine' is not part of the allowed headers. Exiting." 65
 fi
 
 # write the source code to stdout
-printf '%s' "$src"
+printf '%s' "$src" | whitespaceProtection remove
 ) }
-# end module https://mdl.sh/module/fetch/module-fetch-0.9.16.sh
-# start module https://mdl.sh/module/scope/module-scope-0.9.3.sh
+# end module https://mdl.sh/development/module/fetch/module-fetch-0.9.21.sh
+# start module https://mdl.sh/development/module/scope/module-scope-0.9.4.sh
 moduleScope() { (
 set -eu
 name="$1"
@@ -500,34 +597,39 @@ else
 	printf '%s() { (\nset -eu\n%s\n) }\n' "$name" "$moduleContent"
 fi
 ) }
-# end module https://mdl.sh/module/scope/module-scope-0.9.3.sh
-# start module https://mdl.sh/module/validate/module-validate-0.9.6.sh
+# end module https://mdl.sh/development/module/scope/module-scope-0.9.4.sh
+# start module https://mdl.sh/development/module/validate/module-validate-0.9.8.sh
 moduleValidate() { (
 set -eu
-src="$1"
-targetHash="$2"
-
-# start module https://mdl.sh/module/checksum/module-checksum-0.9.5.sh
-moduleChecksum() { (
-set -eu
 # check number of arguments
-if [ "$#" -lt 1 ] || [ "$#" -gt 2 ]; then
+if [ "$#" -ne 2 ]; then
 	printf 'Invalid number of arguments\n' >&2
 	exit 64
 fi
 
-# mandatory:
-# content
-content="$1"
+# mandatory parameters
+src="$1"
+targetHash="$2"
+
+# dependencies
+if [ "$(command -v module 2>/dev/null | cut -c1)" = "/" ]; then eval "$(module init)"; elif ! command -v module >/dev/null 2>&1; then eval "$(h=mdl.sh; p=/latest; u="https://$h$p"; curl -fsL "$u" || wget -q "$u" -O - || ( printf 'GET %s HTTP/1.1\r\nHost: %s\r\nConnection: close\r\n\r\n' "$p" "$h" | openssl s_client -quiet -connect "$h:443" 2>/dev/null | sed '1,/^\r$/d') )"; fi
+# start module https://mdl.sh/development/module/checksum/module-checksum-1.0.0.sh
+moduleChecksum() { (
+set -eu
+# check number of arguments
+if [ "$#" -gt 1 ]; then
+	printf 'Invalid number of arguments\n' >&2
+	exit 64
+fi
 
 # optional:
 # command to calculate the hash, examples:
 # cksum (default, POSIX compliant, weak)
 # md5sum (fast)
 # sha256sum (secure)
-hashCmd="${2:-cksum}"
+hashCmd="${1:-cksum}"
 
-# start module https://mdl.sh/error/error-1.0.3.sh
+# start module https://mdl.sh/development/error/error-1.0.4.sh
 error() {
 # guarantees: intentional-side-effects
 
@@ -542,25 +644,29 @@ error() {
 printf '%s\n' "$1" >&2
 exit "${2:-1}"
 }
-# end module https://mdl.sh/error/error-1.0.3.sh
+# end module https://mdl.sh/development/error/error-1.0.4.sh
 
 if ! command -v "$hashCmd" >/dev/null 2>&1; then
 	error "Checksum command '$hashCmd' is not available. Exiting." 69
 fi
 
+# the content should come from a pipe in order to allow untrimmed whitespace
+# as a parameter it is possible too, but putting the whitespace in a
+# variable is kinda complicated because sub-shells remove it
+
 printf '%s-' "$hashCmd"
-printf '%s' "$content" | "$hashCmd" | tr -s '[:blank:]' ' ' | cut -d ' ' -f1
+cat - | "$hashCmd" | tr -s '[:blank:]' ' ' | cut -d ' ' -f1
 printf '\n'
 ) }
-# end module https://mdl.sh/module/checksum/module-checksum-0.9.5.sh
+# end module https://mdl.sh/development/module/checksum/module-checksum-1.0.0.sh
 
 hashFunc="$(printf '%s' "$targetHash" | cut -d '-' -f1)"
-srcHash="$(moduleChecksum "$src" "$hashFunc")"
+srcHash="$(printf '%s' "$src" | moduleChecksum "$hashFunc")" || exit 65
 if [ "$srcHash" != "$targetHash" ]; then
-	return 1
+	exit 1
 fi
 ) }
-# end module https://mdl.sh/module/validate/module-validate-0.9.6.sh
+# end module https://mdl.sh/development/module/validate/module-validate-0.9.8.sh
 
 		# set other parameters
 		name="$1"
@@ -607,4 +713,4 @@ fi
 	fi
 )"
 }
-# end module https://mdl.sh/module/core/module-core-0.9.17.sh
+# end module https://mdl.sh/development/module/core/module-core-0.9.19.sh
